[[main]]
  name = "Curriculum"
  url = "/curriculum"
  weight = 1000

[[main]]
  name = "Pre-Requisites"
  url = "/pre-reqs"
  weight = 2000

[[main]]
  name = "Resources"
  url = "/libp2p/lorem/ipsum/"
  weight = 3000

[[main]]
  name = "Website"
  url = "https://pl-launchpad.io"
  weight = 4000

# [[main]]
#   name = "Get Started"
#   weight = 30
#   identifier = "get-started"
#   url = "/docs/prologue/introduction/"
#
# [[main]]
#   name = "Quick Start"
#   weight = 40
#   identifier = "quick-start"
#   url = "/docs/prologue/quick-start/"
#   parent = "get-started"
#
# [[main]]
#   name = "Tutorial"
#   weight = 50
#   identifier = "tutorial"
#   url = "https://getdoks.org/tutorial/introduction/"
#   parent = "get-started"



[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/protocol/launchpad"
  post = "v0.1.0"
  weight = 10

[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
  url = "https://twitter.com/launchpad_pl"
  weight = 20


[[curriculum]]
  name = "Protocol Labs Network"
  weight = 10
  identifier = "curriculum-pln"
  url = "/curriculum/get-started/what-is-lotus"
  [curriculum.params]
    image = "https://pbs.twimg.com/profile_images/1266018477694910471/1dlxWC0A_400x400.png"
    section = "pln"
    description = "The Protocol Labs Network includes companies that believe in Web3 and decentralization. Discover the different organizations that are part of the ecosystem!"

[[curriculum]]
  name = "IPFS"
  weight = 20
  identifier = "curriculum-ipfs"
  url = "/curriculum/get-started/what-is-lotus"
  [curriculum.params]
    image = "https://docs.ipfs.io/images/ipfs-logo.svg"
    section = "ipfs"
    description = "IPFS is a peer to peer network in which files are retrieved by their content, instead of their location. Learn what are the benefits (and drawbacks) of using content addressing!"

[[curriculum]]
  name = "IPLD"
  weight = 30
  identifier = "curriculum-ipld"
  url = "/curriculum/get-started/what-is-lotus"
  [curriculum.params]
    image = "https://ipld.io/img/ipld-logo.png"
    section = "ipld"
    description = "IPLD includes a set of protocols and data structures that empower content addressing platforms, such as IPFS. Learn how can you use this tools in your own project!"

[[curriculum]]
  name = "Libp2p"
  weight = 40
  identifier = "curriculum-libp2p"
  url = "/curriculum/get-started/what-is-lotus"
  [curriculum.params]
    image = "https://raw.githubusercontent.com/libp2p/libp2p/a13997787e57d40d6315b422afbe1ceb62f45511/logo/libp2p-logo.png"
    section = "libp2p"
    description = "Libp2p is the networking stack of IPFS, which aims to provide reusable networking pieces for your project!"

[[curriculum]]
  name = "Filecoin"
  weight = 50
  identifier = "curriculum-filecoin"
  url = "/curriculum/get-started/what-is-lotus"
  [curriculum.params]
    image = "https://cryptologos.cc/logos/filecoin-fil-logo.png"
    section = "Filecoin"
    description = "Filecoin a decentralized storage network to store large datasets in an affordable and reliable way"


# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10
